/* * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
 * Copyright by The HDF Group.                                               *
 * All rights reserved.                                                      *
 *                                                                           *
 * This file is part of HDF5.  The full HDF5 copyright notice, including     *
 * terms governing use, modification, and redistribution, is contained in    *
 * the COPYING file, which can be found at the root of the source code       *
 * distribution tree, or in https://www.hdfgroup.org/licenses.               *
 * If you do not have access to either file, you may request a copy from     *
 * help@hdfgroup.org.                                                        *
 * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * */

#ifndef H5_API_TEST_H
#define H5_API_TEST_H

#include <hdf5.h>
#include <H5private.h>

#include "h5test.h"
#include "testframe.h"

#include "H5_api_test_config.h"
#include "H5_api_test_util.h"

/* Define H5VL_VERSION if not already defined */
#ifndef H5VL_VERSION
#define H5VL_VERSION 0
#endif

/* Define macro to wait forever depending on version */
#if H5VL_VERSION >= 2
#define H5_API_TEST_WAIT_FOREVER H5ES_WAIT_FOREVER
#else
#define H5_API_TEST_WAIT_FOREVER UINT64_MAX
#endif

/*
 * Convenience macro to check if API tests are running in
 * multi-threaded mode. If the -maxthreads command-line option
 * is specified with a particular value greater than 0, the API
 * tests are run in multi-threaded mode.
 */
#define H5_API_TEST_EXECUTION_THREADED (GetTestMaxNumThreads() >= 1)

/*
 * Convenience macro to check if API tests are running
 * concurrently in multi-threaded mode. If the -maxthreads
 * command-line option is specified with a particular value
 * greater than 1, the API tests are run concurrently in
 * multi-threaded mode. Otherwise, the API tests either
 * aren't being run in multi-threaded mode, or are only
 * being run from 1 thread in multi-threaded mode.
 */
#define H5_API_TEST_EXECUTION_CONCURRENT (GetTestMaxNumThreads() > 1)

/* Macro for pointer to filename of file used by API tests */
#define H5_API_TEST_FILENAME(TestParamsPtr) \
    (H5_API_TEST_EXECUTION_THREADED ? H5_api_test_filenames_g[(TestParamsPtr)->MtTestParams.ThreadID] : H5_api_test_filenames_g[0])

#define H5_API_TEST_FILENAME_MAX_LENGTH 1024

/*
 * Environment variable specifying a prefix string to add to
 * filenames generated by the API tests
 */
#define HDF5_API_TEST_PATH_PREFIX "HDF5_API_TEST_PATH_PREFIX"

/* The names of a set of container groups which hold objects
 * created by each of the different types of tests.
 */
#define GROUP_TEST_GROUP_NAME         "group_tests"
#define ATTRIBUTE_TEST_GROUP_NAME     "attribute_tests"
#define DATASET_TEST_GROUP_NAME       "dataset_tests"
#define DATATYPE_TEST_GROUP_NAME      "datatype_tests"
#define LINK_TEST_GROUP_NAME          "link_tests"
#define OBJECT_TEST_GROUP_NAME        "object_tests"
#define MISCELLANEOUS_TEST_GROUP_NAME "miscellaneous_tests"

#define ARRAY_LENGTH(array) sizeof(array) / sizeof(array[0])

#define UNUSED(o) (void)(o);

/* The maximum size of a dimension in an HDF5 dataspace as allowed
 * for this testing suite so as not to try to create too large
 * of a dataspace/datatype. */
#define MAX_DIM_SIZE 16

/* Array of filenames used by the API tests. Will
 * contain only a single entry if running tests
 * serially. If running tests in a multi-threaded
 * manner, will contain a thread-local filename for
 * each thread, up to GetTestMaxNumThreads().
 */
extern char **H5_api_test_filenames_g;

/* Prefix to use for filepaths in API tests */
extern const char *test_path_prefix;

#endif
