name: Build and Test HDF5 Library

on:
    push:
        branches:
            - '*'

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                api_tests: ["--enable-api-tests", "--disable-api-tests"]
                multi_thread: ["--enable-multithread --disable-hl", "--disable-multithread --enable-threadsafe --disable-hl", "--disable-multithread --disable-threadsafe"]
            fail-fast: false

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up autotools
              run: |
                  sudo apt install automake autoconf libtool libtool-bin
                  sudo apt install libaec0 libaec-dev valgrind

            - name: Configure HDF5
              working-directory: ${{github.workspace}}
              run: |
                    sh ./autogen.sh
                    ./configure --enable-shared --enable-tests ${{ matrix.multi_thread }} ${{ matrix.api_tests }}

            - name: Build HDF5
              working-directory: ${{github.workspace}}
              run: |
                    make -j

            - name: Find mt vl tests
              working-directory: ${{github.workspace}}
              run: |
                find . -name "*mt_vl_test*"
        
            - name: API Tests
              if: matrix.api_tests == '--enable-api-tests'
              working-directory: ${{github.workspace}}
              run: |
                valgrind ./test/API/api_tests

            - name: Multithread H5VL Tests
              working-directory: ${{github.workspace}}
              run: |
                valgrind ./test/threads/unit/mt_vl_test

            - name: Test HDF5
              working-directory: ${{github.workspace}}
              run: |
                    make check